### ISSUE TITLE
Hardware breakpoints cannot be deleted -> if Address no longer exists

### ISSUE THREAD

**Issue by winkerbie** [x64dbg/x64dbg#1456]
This is a problem of both x32 and x64 dbg
Windows 10 x64

After debugging a program loaded at certain address apace (e.g. 0x00400000), and using hardware breakpoints, those breakpoints are saved into the database file.

However if I debug that program at the later date and it is loaded into a different Address space (e.g. 0x00800000), those saved (absolute address) hardware breakpoints are no longer valid. Worse still I cannot delete those old hardware breakpoints, the debugger just displays an error saying "address doesn't exist"

Major Bug...

**Comment by lupier** [comment]
I can recommend turn off ASLR (at your own risk) or set DYNAMICBASE in compiler to something fixed like 0x30000000 or set "relocation stripped" flag in PE header.

**Comment by mrexodia** [comment]
Are these hardware breakpoints placed inside module code?

**Comment by winkerbie** [comment]
No sorry I should have been clearer

It has only happened when hwbp are placed in DLLs loaded by the exe, therefore very likely to change base address if reloaded

**Comment by mrexodia** [comment]
Any module (including dlls) should automatically be corrected for aslr.

**Comment by winkerbie** [comment]
yes that's what I thought.
It works for software breakpoints but the hardware breakpoints get stuck. 

I will try and get a screenshot

**Comment by winkerbie** [comment]
I realize what was happening...
If the DLL hasn not yet been loaded then the breakpoints (hardware/software) cannot be deleted.
The debug registers remain empty though

I guess it no big deal...

**Comment by winkerbie** [comment]
Maybe you could add an option to hide breakpoints of DLLs that have not yet been loaded?

**Comment by mrexodia** [comment]
@winkerbie that's what the 'Status' is for. It should show 'Inactive' however I do plan to add support for deleting breakpoints that don't exist yet but at the moment I'm quite busy so I cannot.

**Comment by Ahmadmansoor** [comment]
For now you can chose the new address and right click,then chose hw-bp and replace the slot with invalid one

**Comment by atar-axis** [comment]
Unfortunately that problem still persists, that's especially a problem on self-modifying code - as malware often is :(

**Comment by torusrxxx** [comment]
Is this issue fixed by #1965?

**Comment by idevnasty** [comment]
problem still exists and is very annoying

**Comment by mrexodia** [comment]
@idevnasty could you post reproduction steps? I fixed it yesterday I thought...

**Comment by idevnasty** [comment]
I debug a maleware as a sub module dll of an exe. The dll always loads in different places in the memory and not always in the same place. if I set a hw breakpoint and the maleware kills himself, the problem is there. I reload the process where the dll loads in a different location in memory so that the hw breakpoints become ineffective. If I have previously set 3 hw breakpoints, I always get the message that only 4 hw breakpoints are possible. I can not delete or disable that. In my example the dll was packed or secured with VMProtect. I used latest development build.

**Comment by mrexodia** [comment]
So basically there is a VirtualAlloc (or similar), the malware maps the module there and you set a hardware breakpoint? Then restart and you cannot delete the hardware breakpoint again?

For your case the solution is to use a virtual module (virtualmod command or right click on the page in the memory map). This way the hardware breakpoint will have a module+rva and the next time you call virtualmod (for example in a breakpoint command where you know mapping has completed) the hardware breakpoint will be preserved.

**Comment by idevnasty** [comment]
> This is a problem of both x32 and x64 dbg
> Windows 10 x64
> 
> After debugging a program loaded at certain address apace (e.g. 0x00400000), and using hardware breakpoints, those breakpoints are saved into the database file.
> 
> However if I debug that program at the later date and it is loaded into a different Address space (e.g. 0x00800000), those saved (absolute address) hardware breakpoints are no longer valid. Worse still I cannot delete those old hardware breakpoints, the debugger just displays an error saying "address doesn't exist"
> 
> Major Bug...

this is the same problem that has already been described in the first post

**Comment by mrexodia** [comment]
I tested and this issue has been resolved. Inactive hardware breakpoints without modules can be deleted without any issues from the GUI.

**Comment by idevnasty** [comment]
im on snapshot snapshot_2020-04-02_00-35.zip 
see the video describes  https://streamable.com/u31dtc

**Comment by mrexodia** [comment]
It would be helpful to see how the hardware breakpoints are created.

**Comment by lupier** [comment]
Problem still exists in latest snapshot for simple BP (non hardware).
Problem can be reproduced in next way:
1st stage - load DLL with big code section at 0x10000000
Place BP in DLL at 0x100E7000 (as example)
2nd stage - recompile DLL and reduce it's size (by any possible way)
Restart debugging - now DLL loaded at same 0x10000000 but it's image in memory do not cover address 0x100E7000 anymore!
And now you will see non existing BP "100E7000 | mydll.dll | Inactive"

**Comment by lupier** [comment]
Build from May, 15: Invalid BP, still cannot remove non-existing breakpoints

**Comment by mrexodia** [comment]
Please provide reproduction steps, because I cannot reproduce this.

**Comment by lupier** [comment]
Prepare two copies of the same library. One copy with a lot of code, the second copy with a minimum amount of code.
We put a breakpoint in the first library at the most large available address in this dll memory, such that it is guaranteed not to exist in the library with a smaller code size.
Now replace this library and run debugger again, breakpoint from the previous version no longer exists because it refers to an address that is not exists in the smaller library.
Example: BP 0x1003500E at code section from big code lib.
Same DLL with lower code section size: 0x1001000 is the last available adress in whole DLL, so BP became invalid

**Comment by lupier** [comment]
1) testme1.dll place BP at 0x10005983 
2) close debugger and replace testme1.dll with testme2.dll (rename testme2.dll to testme1.dll)
3) restart debugger, BP became invalid
[test.zip](https://github.com/x64dbg/x64dbg/files/4706069/test.zip)

**Comment by lupier** [comment]
![Screenshot_41](https://user-images.githubusercontent.com/1623540/83553336-7b0bd480-a524-11ea-8a70-e6aaa087188a.png)
Additional information: same address for invalid BP and valid BP. Valid BP from dbghelp (see screenshot) can be removed. Invalid BP from another module still exists.

**Comment by mrexodia** [comment]
Thanks, I think I know where the issue is. I’ll look into it :)

**Comment by ncatlin** [comment]
+1 to this issue, debugging something that detect HW breakpoints and being unable to clear DR7 was driving me insane.
For a temporary fix to anyone else with the problem, you can decompress your DB with the undocumented  "dbdecompress [path]" command and manually change the breakpoint to "enabled": false in a text editor.

**Comment by abdellatif10** [comment]
I replaced in the function 

> bool BpEnumAll(BPENUMCALLBACK EnumCallback, const char* Module, duint base)

of
 
> src\dbg\breakpoint.cpp

        BREAKPOINT bpInfo = j->second;
        if(bpInfo.type != BPDLL && bpInfo.type != BPEXCEPTION)
        {
            if(base) //workaround for some Windows bullshit with compatibility mode
                bpInfo.addr += base;
            else
                bpInfo.addr += ModBaseFromName(bpInfo.mod);
        }
        setBpActive(bpInfo);

        BREAKPOINT bpInfo = j->second, found;
        if(bpInfo.type != BPDLL && bpInfo.type != BPEXCEPTION)
        {
            if(base) //workaround for some Windows bullshit with compatibility mode
                bpInfo.addr += base;
            else
            {
                char arg[deflen];
                sprintf_s(arg, "%s:$%X", bpInfo.mod, bpInfo.addr);
                if(BpGet(0, bpInfo.type, arg, &found)) //found a breakpoint with name
                    bpInfo = found;
            }
        }
        setBpActive(bpInfo);

it seems to work for me.

**Comment by mrexodia** [comment]
> I replaced in the function
> 
> > bool BpEnumAll(BPENUMCALLBACK EnumCallback, const char* Module, duint base)
> 
> of
> 
> > src\dbg\breakpoint.cpp
> 
> ```
>     BREAKPOINT bpInfo = j->second;
>     if(bpInfo.type != BPDLL && bpInfo.type != BPEXCEPTION)
>     {
>         if(base) //workaround for some Windows bullshit with compatibility mode
>             bpInfo.addr += base;
>         else
>             bpInfo.addr += ModBaseFromName(bpInfo.mod);
>     }
>     setBpActive(bpInfo);
> 
>     BREAKPOINT bpInfo = j->second, found;
>     if(bpInfo.type != BPDLL && bpInfo.type != BPEXCEPTION)
>     {
>         if(base) //workaround for some Windows bullshit with compatibility mode
>             bpInfo.addr += base;
>         else
>         {
>             char arg[deflen];
>             sprintf_s(arg, "%s:$%X", bpInfo.mod, bpInfo.addr);
>             if(BpGet(0, bpInfo.type, arg, &found)) //found a breakpoint with name
>                 bpInfo = found;
>         }
>     }
>     setBpActive(bpInfo);
> ```
> 
> it seems to work for me.

That's great! It would be cool if you could send a pull request so we can get a build, review things etc 🙂

**Comment by abdellatif10** [comment]
@ mrexodia, sorry I don't know how to do that.
